import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server-client";
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from "docx";

export const maxDuration = 30;

export async function POST(req) {
  try {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

    const { fileName, messages } = await req.json();
    if (!Array.isArray(messages) || messages.length === 0) {
      return NextResponse.json({ error: "No messages to export" }, { status: 400 });
    }

    const children = [
      new Paragraph({
        text: `Q&A Export: ${fileName ?? "Document"}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [
          new TextRun({
            text: `Generated by Intellixy AI · ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}`,
            color: "888888",
            size: 18,
          }),
        ],
        spacing: { after: 400 },
      }),
    ];

    let qIndex = 0;
    for (let i = 0; i < messages.length; i++) {
      const msg = messages[i];
      if (msg.role === "user") {
        qIndex++;
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `Q${qIndex}: `, bold: true, color: "2563EB", size: 22 }),
              new TextRun({ text: msg.text, bold: true, size: 22 }),
            ],
            spacing: { before: 300, after: 100 },
            border: {
              left: { style: BorderStyle.SINGLE, size: 6, color: "2563EB", space: 8 },
            },
          })
        );
      } else {
        // Strip markdown-ish formatting for plain text output
        const plain = msg.text
          .replace(/\*\*(.+?)\*\*/g, "$1")
          .replace(/\*(.+?)\*/g, "$1")
          .replace(/^#{1,3}\s+/gm, "")
          .replace(/^[-•]\s+/gm, "• ");

        const lines = plain.split("\n").filter(l => l.trim());
        for (const line of lines) {
          const isBullet = line.startsWith("• ");
          children.push(
            new Paragraph({
              children: [
                new TextRun({
                  text: isBullet ? line : line,
                  size: 20,
                  color: "333333",
                }),
              ],
              bullet: isBullet ? { level: 0 } : undefined,
              spacing: { after: 60 },
              alignment: AlignmentType.LEFT,
            })
          );
        }
        children.push(new Paragraph({ text: "", spacing: { after: 200 } }));
      }
    }

    const doc = new Document({
      creator: "Intellixy AI",
      title: `${fileName ?? "Document"} Q&A`,
      description: "AI-generated Q&A export from Intellixy",
      sections: [{ children }],
    });

    const buffer = await Packer.toBuffer(doc);

    return new Response(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${(fileName ?? "export").replace(/[^\w\s-]/g, "")}-qa.docx"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    console.error("[export-chat] Error:", err.message);
    return NextResponse.json({ error: "Export failed" }, { status: 500 });
  }
}
